### ISSUE TITLE
Task List Design

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica-android#23]
- [ ] custom checkbox design for dailies and todos
- [ ] more whitespace
- [ ] updated colors from brandbook
- [ ] completed and non-due dailies as gray

Reference Design Screen:

<img width="360" alt="android_habits" src="https://cloud.githubusercontent.com/assets/298062/10827679/8771b1a2-7e70-11e5-968e-45e27eae15b1.png">

<img width="360" alt="android_dailies" src="https://cloud.githubusercontent.com/assets/298062/10827647/6dd31a6a-7e70-11e5-9afc-3d20eb13e594.png">

<img width="360" alt="android_todos" src="https://cloud.githubusercontent.com/assets/298062/10827648/6e010fa6-7e70-11e5-932b-c2cb84c7c357.png">
